GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization:  bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6IjYxOTkxMTI0ZGE0NDhjMWU3YjkwZDhiMyIsImlhdCI6MTYzNzQyNTYxNSwiZXhwIjoxNjM3NDI5MjE1fQ.kYlUtSsqLSME7sNGdX_Qq8AWDiQ-3Ab6_1JSu4P8o1U

{
  "title": "Test 3",
  "author": "Test author 3",
  "likes": 3,
  "url": "www.test3.com"
}