GET http://localhost:3003/api/users

### Valid POST-request
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Test",
    "name": "Test Request",
    "password": "testrequest"
}

### Password too short
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "tooshort",
    "name": "Short Password",
    "password": "sh"
}

### Password missing
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "missing",
    "name": "Missing Password"
}

### Username too short
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "SU",
    "name": "Short Username",
    "password": "passwordlongenough"
}
